/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch Primary & Palette tokens
        "primary": "#0284c7",
        "primary-hover": "#0369a1",
        "primary-light": "#e0f2fe",
        "primary-fixed": "#c9e6ff",
        "primary-fixed-dim": "#89ceff",
        "on-primary": "#ffffff",
        "on-primary-container": "#003751",
        "on-primary-fixed": "#001e2f",
        "on-primary-fixed-variant": "#004c6e",
        "inverse-primary": "#89ceff",

        "secondary": "#0d9488",
        "secondary-light": "#ccfbf1",
        "secondary-container": "#6cf8bb",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00714d",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",

        "tertiary": "#842bd2",
        "tertiary-container": "#bf7dff",
        "tertiary-fixed": "#f0dbff",
        "tertiary-fixed-dim": "#ddb7ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4d0087",
        "on-tertiary-fixed": "#2c0051",
        "on-tertiary-fixed-variant": "#6900b3",

        "accent-coral": "#f43f5e",
        "accent-warm": "#f59e0b",
        "accent-purple": "#8b5cf6",

        "surface-pure": "#ffffff",
        "surface-subtle": "#f8fafc",
        "surface-soft": "#f0f9ff",
        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#006591",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "background": "#f8f9ff",
        "on-background": "#0b1c30",

        "on-surface": "#0f172a",
        "on-surface-variant": "#475569",
        "border-soft": "#e2e8f0",
        "border-pastel": "#bae6fd",
        "outline": "#6e7881",
        "outline-variant": "#bec8d2",

        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      maxWidth: {
        "2xl": "43rem",
      },
      borderRadius: {
        "DEFAULT": "0.375rem",
        "sm": "0.25rem",
        "md": "0.375rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.25rem",
        "3xl": "1.75rem",
        "full": "9999px",
      },
      spacing: {
        "gutter": "1.5rem",
        "gutter-sm": "0.75rem",
        "gutter-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "2rem",
        "margin-sm": "1rem",
        "margin-md": "2rem",
        "margin-lg": "3rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
      },
      fontFamily: {
        "body-sm": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
        "title-sm": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
        "title-md": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
        "label-lg": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
        "display-lg": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
        "display-lg-mobile": ["'Plus Jakarta Sans'", "'Noto Sans KR'", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["30px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["28px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "title-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      boxShadow: {
        "xs": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        "2xs": "0 1px 1px 0 rgba(0, 0, 0, 0.03)",
      },
      dropShadow: {
        "xs": "0 1px 1px rgba(0, 0, 0, 0.05)",
        "sm": "0 1px 2px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [],
};
